### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by paopaosa** [JyHu/Fella#2]
每次导出全部的时候，能不能只弹一个框，要是很多localized项目的时候，它会弹好几次。

**Comment by JyHu** [comment]
收到，下个版本就优化，因为我这边平时在导出的时候都是单个导出的，没有太强的感觉。

> 每次导出全部的时候，能不能只弹一个框，要是很多localized项目的时候，它会弹好几次。

**Comment by paopaosa** [comment]
挺好的，还有个建议能不能把背景的风车动画给关了。我看它挺占Window Server的资源。

**Comment by JyHu** [comment]
> 

后续我加个控制开关吧。

**Comment by paopaosa** [comment]
嗯。因为动画能耗比挺高的，可以考虑优化一下，程序切换后台的时候，自动停止这个动画之类的。有时候我改项目一直开着fella，然后离开了，回来后机器很热，发现是这个程序CPU占用的window server一直在40以上。
